# Generated by Django 4.2.20 on 2025-11-04 03:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('employee_verification', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('cdl_number', models.CharField(blank=True, default='', max_length=255)),
                ('cdl_expiration_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('physical_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('annual_vmr_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('dob', models.DateField(blank=True, default=datetime.date(1990, 1, 1), null=True)),
                ('ssn', models.CharField(blank=True, default='', max_length=11)),
                ('hire_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('random_test_required_this_year', models.BooleanField(default=True, editable=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MercAPI.company')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('pre-trip', 'Pre-trip'), ('post-trip', 'Post-trip'), ('annual', 'Annual')], max_length=20)),
                ('inspection_date', models.DateTimeField(default=datetime.datetime.now)),
                ('defects_found', models.BooleanField(default=False)),
                ('overall_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signed_by', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_number', models.CharField(default='UNKNOWN', max_length=50, unique=True)),
                ('vin', models.CharField(default='UNKNOWN', max_length=17)),
                ('license_plate', models.CharField(max_length=20)),
                ('license_plate_state', models.CharField(default='NA', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(default='UNKNOWN', max_length=255)),
                ('model', models.CharField(default='UNKNOWN', max_length=255)),
                ('license_plate_expiration', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('registration_expiration', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('insurance_expiration', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('annual_dot_inspection_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercAPI.company')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.TextField()),
                ('end_location', models.TextField(blank=True, null=True)),
                ('miles_driven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='MercAPI.driver')),
                ('post_trip_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_trip_trips', to='MercAPI.inspection')),
                ('pre_trip_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_trip_trips', to='MercAPI.inspection')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='MercAPI.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercAPI.company')),
                ('truck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.truck')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('brakes', 'Brakes'), ('steering', 'Steering'), ('lights', 'Lights'), ('tires', 'Tires'), ('horn', 'Horn'), ('wipers', 'Wipers'), ('mirrors', 'Mirrors'), ('coupling', 'Coupling'), ('emergency_equipment', 'Emergency Equipment')], max_length=50)),
                ('condition', models.CharField(choices=[('ok', 'OK'), ('defect', 'Defect'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MercAPI.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.truck'),
        ),
        migrations.CreateModel(
            name='DriverTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('Pre-employment', 'Pre-employment'), ('Random', 'Random'), ('Post-Accident', 'Post-Accident'), ('Reasonable suspicion', 'Reasonable suspicion'), ('Return-to-duty', 'Return-to-duty'), ('Follow-up', 'Follow-up')], max_length=50)),
                ('test_date', models.DateField()),
                ('test_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], max_length=20)),
                ('random_test_required_this_year', models.BooleanField(default=False)),
                ('test_completion_date', models.DateField(blank=True, null=True)),
                ('next_scheduled_test_date', models.DateField(blank=True, null=True)),
                ('follow_up_test_required', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='MercAPI.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverHOS',
            fields=[
                ('hos_id', models.AutoField(primary_key=True, serialize=False)),
                ('duty_date', models.DateField()),
                ('duty_status', models.CharField(choices=[('OFF', 'Off Duty'), ('SLEEP', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('miles_driven', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_records', to='MercAPI.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hos_records', to='MercAPI.trips')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hos_records', to='MercAPI.truck')),
            ],
        ),
    ]
