# Generated by Django 4.2.20 on 2025-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0002_create_driverapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='cdla_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
