# Generated by Django 4.2.20 on 2025-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercApi', '0002_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
