# Generated by Django 4.2.20 on 2025-11-05 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0003_driverapplication_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
