# Generated by Django 4.2.20 on 2025-04-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MercApi', '0003_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
