# Generated by Django 4.2.20 on 2025-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercApi', '0004_delete_company_delete_trailer_delete_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='annual_vmr_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='cdl_expiration_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='cdl_number',
            field=models.CharField(default='00000', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.CharField(blank=True, default='Unknown Company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True, default='1990-01-01', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='employee_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='000-0000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='physical_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ssn',
            field=models.CharField(default='000-00-0000', max_length=11),
        ),
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
