# Generated by Django 4.2.20 on 2025-04-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercApi', '0005_remove_driver_email_remove_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
