# Generated by Django 4.2.20 on 2025-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0005_maintenancecategory_maintenancetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('oil_change', 'Oil Change'), ('transmission_service', 'Transmission Service'), ('differential_service', 'Differential Service'), ('engine_tune_up', 'Engine Tune-Up'), ('brake_inspection', 'Brake Inspection'), ('brake_pad_replacement', 'Brake Pad Replacement'), ('air_brake_service', 'Air Brake Service'), ('tire_rotation', 'Tire Rotation'), ('tire_replacement', 'Tire Replacement'), ('wheel_alignment', 'Wheel Alignment'), ('lighting_inspection', 'Lighting Inspection'), ('battery_service', 'Battery Service'), ('alternator_service', 'Alternator Service'), ('ac_service', 'A/C Service'), ('heater_service', 'Heater Service'), ('body_repair', 'Body Repair'), ('frame_inspection', 'Frame Inspection'), ('a_service', 'A-Service (Basic)'), ('b_service', 'B-Service (Intermediate)'), ('c_service', 'C-Service (Complete)'), ('annual_dot_inspection', 'Annual DOT Inspection'), ('quarterly_inspection', '90-Day Inspection'), ('pre_trip_inspection', 'Pre-Trip Inspection'), ('other', 'Other')], max_length=50),
        ),
    ]
