# Generated by Django 4.2.20 on 2025-11-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0006_change_maintenance_type_to_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='maintenanceattachment',
            name='file_path',
        ),
        migrations.AddField(
            model_name='maintenanceattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='maintenanceattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceattachment',
            name='uploaded_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='document', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cdl_license', 'CDL License'), ('medical_certificate', 'Medical Certificate'), ('mvr_report', 'Motor Vehicle Record'), ('employment_verification', 'Employment Verification'), ('drug_test_results', 'Drug Test Results'), ('background_check', 'Background Check'), ('training_certificate', 'Training Certificate'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='driver_documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(default='system', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='MercAPI.driver')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
