# Generated by Django 4.2.20 on 2025-04-16 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercApi', '0007_company_alter_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='annual_vmr_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cdl_expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cdl_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MercApi.company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='physical_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercApi.company')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercApi.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercApi.company')),
                ('truck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercApi.truck')),
            ],
        ),
    ]
