# Generated by Django 4.2.20 on 2025-11-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0007_add_file_upload_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='drivers_license',
            field=models.FileField(blank=True, help_text="Upload driver's license image", null=True, upload_to='applications/licenses/'),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='medical_certificate',
            field=models.FileField(blank=True, help_text='Upload medical certificate/DOT physical', null=True, upload_to='applications/medical/'),
        ),
    ]
