# Generated by Django 4.2.20 on 2025-11-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0008_add_file_fields_to_driver_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Business name (e.g., 'ABC Logistics LLC')", max_length=255)),
                ('domain', models.CharField(help_text="Subdomain for this tenant (e.g., 'abc-logistics')", max_length=100, unique=True)),
                ('application_code', models.CharField(help_text="Short code for Quick Apply links (e.g., 'ABC123')", max_length=10, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email for this tenant', max_length=254)),
                ('subscription_plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant (Business Account)',
                'verbose_name_plural': 'Tenants (Business Accounts)',
                'ordering': ['name'],
            },
        ),
    ]
