# Generated by Django 4.2.20 on 2025-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercApi', '0008_alter_driver_annual_vmr_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cdl_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
