# Generated by Django 4.2.20 on 2025-11-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0009_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The business/organization this company belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='MercAPI.tenant'),
        ),
    ]
