# Generated by Django 4.2.20 on 2025-11-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0010_company_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly name for this company (e.g., 'east-coast', 'west-division')", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The specific company/division this application is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='MercAPI.company'),
        ),
    ]
