# Generated by Django 4.2.20 on 2025-11-06 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0011_company_slug_driverapplication_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_admin', models.BooleanField(default=False, help_text='Can this user manage company settings and other users?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, help_text='Companies this user has access to', to='MercAPI.company')),
                ('tenant', models.ForeignKey(blank=True, help_text='Primary tenant this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='MercAPI.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
