# Generated by Django 4.2.20 on 2025-11-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0013_invitationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.CharField(blank=True, help_text="User's profile photo path (temporarily CharField)", max_length=255, null=True),
        ),
    ]
