# Generated by Django 4.2.20 on 2025-11-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0014_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, help_text="User's profile photo file", null=True, upload_to='profile_photos/%Y/%m/%d/'),
        ),
    ]
