# Generated by Django 4.2.20 on 2025-11-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0015_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_photo',
            new_name='profile_image',
        ),
    ]
