# Generated by Django 4.2.20 on 2025-11-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0016_rename_profile_photo_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin - Full tenant management access'), ('user', 'User - Company management access (cannot create companies/users)'), ('driver', 'Driver - Inspection and trip access only')], default='user', help_text="User's role level within the tenant", max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Can this user manage company settings and other users? (deprecated - use role field)'),
        ),
    ]
