# Generated by Django 4.2.20 on 2025-11-08 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0017_add_role_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user_account',
            field=models.OneToOneField(blank=True, help_text='Optional user account for driver portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
