# Generated by Django 4.2.20 on 2025-11-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0018_add_user_account_to_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='invitation_data',
            field=models.JSONField(default=dict, help_text='Additional invitation data (role, company_ids, driver_id, etc.)'),
        ),
    ]
