# Generated by Django 4.2.20 on 2025-11-09 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0019_add_invitation_data_json_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['-scheduled_start_date', '-start_time'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trips',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_trips', to='MercAPI.company'),
        ),
        migrations.AddField(
            model_name='trips',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trips',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='mileage_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='mileage_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='post_trip_inspection_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='pre_trip_inspection_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='scheduled_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='scheduled_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='trips',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='MercAPI.trailer'),
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='miles_driven',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TripDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bol', 'Bill of Lading'), ('receipt', 'Receipt'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='trip_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='MercAPI.trips')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Document',
                'verbose_name_plural': 'Trip Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TripInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('pre_trip', 'Pre-Trip'), ('post_trip', 'Post-Trip')], max_length=20)),
                ('vehicle_exterior_condition', models.BooleanField(default=False, help_text='No visible damage, clean')),
                ('lights_working', models.BooleanField(default=False, help_text='All lights functional')),
                ('tires_condition', models.BooleanField(default=False, help_text='Proper pressure, no damage')),
                ('brakes_working', models.BooleanField(default=False, help_text='Brakes responsive')),
                ('engine_fluids_ok', models.BooleanField(default=False, help_text='Oil, coolant, brake fluid levels good')),
                ('trailer_attached_properly', models.BooleanField(default=False, help_text='Securely connected')),
                ('trailer_lights_working', models.BooleanField(default=False, help_text='All trailer lights functional')),
                ('cargo_secured', models.BooleanField(default=False, help_text='Load properly secured')),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('issues_found', models.TextField(blank=True, help_text='Any problems discovered', null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_inspections', to='MercAPI.trips')),
            ],
            options={
                'verbose_name': 'Trip Inspection',
                'verbose_name_plural': 'Trip Inspections',
                'ordering': ['-completed_at'],
                'unique_together': {('trip', 'inspection_type')},
            },
        ),
    ]
