# Generated by Django 4.2.20 on 2025-11-09 03:56

from django.db import migrations, models


def populate_unique_unit_numbers(apps, schema_editor):
    """
    Populate unique unit_numbers for existing trailers to avoid constraint violations
    """
    Trailer = apps.get_model('MercAPI', 'Trailer')
    trailers = Trailer.objects.all()
    
    for i, trailer in enumerate(trailers, 1):
        # Generate unique unit numbers for existing trailers
        if not trailer.unit_number or trailer.unit_number == 'UNKNOWN':
            trailer.unit_number = f'TR-{i:04d}'
            trailer.save()


def reverse_populate_unit_numbers(apps, schema_editor):
    """
    Reverse operation - set all unit_numbers back to UNKNOWN
    """
    Trailer = apps.get_model('MercAPI', 'Trailer')
    Trailer.objects.all().update(unit_number='UNKNOWN')


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0020_alter_trips_options_trips_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='trailer_type',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='trailer',
            name='unit_number',
            field=models.CharField(default='UNKNOWN', max_length=50),  # Remove unique=True initially
        ),
        migrations.RunPython(
            populate_unique_unit_numbers,
            reverse_populate_unit_numbers,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='unit_number',
            field=models.CharField(default='UNKNOWN', max_length=50, unique=True),  # Add unique constraint after populating
        ),
    ]
