# Generated by Django 4.2.20 on 2025-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0022_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='start_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
