# Generated by Django 4.2.20 on 2025-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0023_alter_trips_start_location_alter_trips_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinspection',
            name='brakes_working',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Brakes responsive', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='cargo_secured',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='na', help_text='Load properly secured', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='engine_fluids_ok',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Oil, coolant, brake fluid levels good', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='lights_working',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='All lights functional', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='tires_condition',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Proper pressure, no damage', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='trailer_attached_properly',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='na', help_text='Securely connected', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='trailer_lights_working',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='na', help_text='All trailer lights functional', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='vehicle_exterior_condition',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='No visible damage, clean', max_length=10),
        ),
    ]
