# Generated by Django 4.2.20 on 2025-12-03 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0024_alter_tripinspection_brakes_working_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinspection',
            name='coupling_devices',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Coupling devices secure', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='emergency_equipment',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Emergency equipment present', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='horn',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Horn operational', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='lighting_devices',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Lighting devices and reflectors', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='parking_brake',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Parking brake operational', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='rear_vision_mirrors',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Rear vision mirrors clean and secure', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='service_brakes',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Service brakes including trailer brake connections', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='steering_mechanism',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Steering mechanism responsive', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='wheels_and_rims',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Wheels and rims - no cracks or damage', max_length=10),
        ),
        migrations.AddField(
            model_name='tripinspection',
            name='windshield_wipers',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Windshield wipers operational', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='brakes_working',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Brakes responsive (legacy - use service_brakes)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='lights_working',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='All lights functional (legacy - use lighting_devices)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripinspection',
            name='tires_condition',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Tires - proper pressure, no damage', max_length=10),
        ),
        migrations.CreateModel(
            name='TripInspectionRepairCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_description', models.TextField(help_text='Description of the defect found during inspection')),
                ('repair_required', models.BooleanField(help_text='Is repair required for safe operation?')),
                ('repair_description', models.TextField(blank=True, help_text='Description of repairs performed', null=True)),
                ('repair_unnecessary_reason', models.TextField(blank=True, help_text='Reason why repair is unnecessary', null=True)),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_safe_to_operate', models.BooleanField(help_text='Vehicle is safe to operate before next use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_by', models.ForeignKey(help_text='Person certifying the repair', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_certifications', to='MercAPI.tripinspection')),
            ],
            options={
                'verbose_name': 'Repair Certification (CFR 396.11)',
                'verbose_name_plural': 'Repair Certifications (CFR 396.11)',
                'ordering': ['-created_at'],
            },
        ),
    ]
