# Generated by Django 4.2.20 on 2025-12-03 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0025_add_cfr_396_11_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer')], max_length=10)),
                ('inspection_date', models.DateField()),
                ('next_inspection_due', models.DateField(help_text='Next annual inspection due date')),
                ('inspection_result', models.CharField(choices=[('pass', 'Pass'), ('conditional_pass', 'Conditional Pass'), ('fail', 'Fail')], max_length=20)),
                ('inspection_certificate_number', models.CharField(max_length=100, unique=True)),
                ('inspection_report_pdf', models.FileField(help_text='PDF copy of annual inspection report (CFR 396.17 requirement)', upload_to='annual_inspections/%Y/%m/')),
                ('defects_found', models.TextField(blank=True, help_text='List of defects found during inspection', null=True)),
                ('conditions_for_pass', models.TextField(blank=True, help_text='Conditions required for conditional pass', null=True)),
                ('repairs_completed', models.BooleanField(default=False)),
                ('repair_completion_date', models.DateField(blank=True, null=True)),
                ('compliant_until', models.DateField(help_text='Vehicle is compliant for operation until this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annual Inspection (CFR 396.17)',
                'verbose_name_plural': 'Annual Inspections (CFR 396.17)',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_reviewed',
            field=models.BooleanField(default=False, help_text='Driver reviewed last DVIR before starting trip (CFR 396.13)'),
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dvirs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VehicleOperationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer')], max_length=10)),
                ('current_status', models.CharField(choices=[('safe', 'Safe to Operate'), ('conditional', 'Conditional Operation'), ('prohibited', 'Operation Prohibited'), ('out_of_service', 'Out of Service')], default='safe', max_length=20)),
                ('status_reason', models.TextField(blank=True, help_text='Reason for current status', null=True)),
                ('status_set_at', models.DateTimeField(auto_now=True)),
                ('clear_status_date', models.DateField(blank=True, help_text='Date when vehicle can return to service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_annual_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.annualinspection')),
                ('related_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.tripinspection')),
                ('related_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.maintenancerecord')),
                ('status_set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_status', to='MercAPI.trailer')),
                ('truck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_status', to='MercAPI.truck')),
            ],
            options={
                'verbose_name': 'Vehicle Operation Status (CFR 396.7)',
                'verbose_name_plural': 'Vehicle Operation Status (CFR 396.7)',
            },
        ),
        migrations.CreateModel(
            name='QualifiedInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_id', models.CharField(help_text='Inspector certification ID', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inspector_type', models.CharField(choices=[('dot_certified', 'DOT Certified Inspector'), ('company_qualified', 'Company Qualified Inspector'), ('external_shop', 'External Shop Inspector')], max_length=20)),
                ('certification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('qualified_for_annual', models.BooleanField(default=False)),
                ('qualified_for_periodic', models.BooleanField(default=False)),
                ('qualified_for_roadside', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_inspectors', to='MercAPI.company')),
            ],
            options={
                'verbose_name': 'Qualified Inspector (CFR 396.19)',
                'verbose_name_plural': 'Qualified Inspectors (CFR 396.19)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='annualinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercAPI.qualifiedinspector'),
        ),
        migrations.AddField(
            model_name='annualinspection',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_inspections', to='MercAPI.trailer'),
        ),
        migrations.AddField(
            model_name='annualinspection',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_inspections', to='MercAPI.truck'),
        ),
    ]
