# Generated by Django 4.2.20 on 2025-12-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0026_add_comprehensive_cfr_compliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='last_dvir_reviewed',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='last_dvir_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='last_dvir_reviewed_by',
        ),
    ]
