# Generated by Django 4.2.20 on 2025-12-04 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0027_remove_dvir_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinspectionrepaircertification',
            name='affects_safety',
            field=models.BooleanField(default=True, help_text='Does this defect affect vehicle safety?'),
        ),
        migrations.AddField(
            model_name='tripinspectionrepaircertification',
            name='repair_completed',
            field=models.BooleanField(default=False, help_text='Has the repair been completed?'),
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_acknowledgment',
            field=models.TextField(blank=True, help_text='Driver acknowledgment text', null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_reviewed',
            field=models.BooleanField(default=False, help_text='Driver reviewed last post-trip DVIR before starting trip'),
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='last_dvir_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvir_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
