# Generated by Django 4.2.20 on 2025-12-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0028_add_dvir_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinspectionrepaircertification',
            name='defect_type',
            field=models.CharField(choices=[('service_brakes', 'Service Brakes (CFR 396.11(a)(1)(i))'), ('parking_brake', 'Parking Brake (CFR 396.11(a)(1)(ii))'), ('steering_mechanism', 'Steering Mechanism (CFR 396.11(a)(1)(iii))'), ('lighting_devices', 'Lighting Devices & Reflectors (CFR 396.11(a)(1)(iv))'), ('tires', 'Tires (CFR 396.11(a)(1)(v))'), ('horn', 'Horn (CFR 396.11(a)(1)(vi))'), ('windshield_wipers', 'Windshield Wipers (CFR 396.11(a)(1)(vii))'), ('rear_vision_mirrors', 'Rear Vision Mirrors (CFR 396.11(a)(1)(viii))'), ('coupling_devices', 'Coupling Devices (CFR 396.11(a)(1)(ix))'), ('wheels_and_rims', 'Wheels and Rims (CFR 396.11(a)(1)(x))'), ('emergency_equipment', 'Emergency Equipment (CFR 396.11(a)(1)(xi))'), ('other', 'Other Safety-Related Defect')], default='other', help_text='Type of defect per CFR 396.11', max_length=25),
        ),
        migrations.AddField(
            model_name='tripinspectionrepaircertification',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, help_text='Associated maintenance record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='tripinspectionrepaircertification',
            name='operation_impact',
            field=models.CharField(choices=[('safe', 'Safe to Operate - No impact on safety'), ('conditional', 'Conditional Operation - Monitor closely'), ('prohibited', 'Operation Prohibited - CFR 396.7 violation'), ('out_of_service', 'Out of Service - Immediate repair required')], default='prohibited', help_text='Impact on vehicle operation per CFR 396.7', max_length=20),
        ),
    ]
