# Generated by Django 4.2.20 on 2025-12-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0029_tripinspectionrepaircertification_defect_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='blocks_operation',
            field=models.BooleanField(default=False, help_text='Whether this maintenance prevents vehicle operation'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='related_trip',
            field=models.ForeignKey(blank=True, help_text='Trip that identified this maintenance need', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_maintenance_records', to='MercAPI.trips'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('maintenance_hold', 'Maintenance Hold'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
