# Generated by Django 4.2.20 on 2025-12-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0030_maintenancerecord_blocks_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for trip cancellation', null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
