# Generated by Django 4.2.20 on 2025-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0031_trips_cancellation_reason_trips_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinspectionrepaircertification',
            name='defect_type',
            field=models.CharField(choices=[('service_brakes', 'Service Brakes (CFR 396.11(a)(1)(i))'), ('parking_brake', 'Parking Brake (CFR 396.11(a)(1)(ii))'), ('steering_mechanism', 'Steering Mechanism (CFR 396.11(a)(1)(iii))'), ('lighting_devices', 'Lighting Devices & Reflectors (CFR 396.11(a)(1)(iv))'), ('tires', 'Tires (CFR 396.11(a)(1)(v))'), ('horn', 'Horn (CFR 396.11(a)(1)(vi))'), ('windshield_wipers', 'Windshield Wipers (CFR 396.11(a)(1)(vii))'), ('rear_vision_mirrors', 'Rear Vision Mirrors (CFR 396.11(a)(1)(viii))'), ('coupling_devices', 'Coupling Devices (CFR 396.11(a)(1)(ix))'), ('wheels_and_rims', 'Wheels and Rims (CFR 396.11(a)(1)(x))'), ('emergency_equipment', 'Emergency Equipment (CFR 396.11(a)(1)(xi))'), ('vehicle_exterior', 'Vehicle Exterior Condition'), ('engine_fluids', 'Engine Fluids & Systems'), ('trailer_coupling', 'Trailer Coupling & Attachment'), ('cargo_securement', 'Cargo Security & Load'), ('other', 'Other Safety-Related Defect')], default='other', help_text='Type of defect per CFR 396.11', max_length=25),
        ),
    ]
