# Generated by Django 4.2.20 on 2025-12-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0032_alter_tripinspectionrepaircertification_defect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('failed_inspection', 'Failed Inspection'), ('maintenance_hold', 'Maintenance Hold'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
