# Generated by Django 4.2.20 on 2025-12-04 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0033_alter_trips_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Vehicle Inspection', 'verbose_name_plural': 'Vehicle Inspections'},
        ),
        migrations.AddField(
            model_name='inspection',
            name='brakes_working',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Legacy field for brakes (use service_brakes instead)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cargo_secured',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Cargo properly secured', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.company'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='When inspection was completed'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='coupling_devices',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Coupling devices secure', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='defects_description',
            field=models.TextField(blank=True, help_text='Detailed description of defects found', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='emergency_equipment',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Emergency equipment present and functional', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='engine_fluids_ok',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Engine oil, coolant, brake fluid levels', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='horn',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Horn functional', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_notes',
            field=models.TextField(blank=True, help_text='Additional inspection notes', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='issues_found',
            field=models.TextField(blank=True, help_text='Issues identified during inspection', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='lighting_devices',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Lighting devices and reflectors', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='lights_working',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Legacy field for lights (use lighting_devices instead)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='maintenance_description',
            field=models.TextField(blank=True, help_text='Description of required maintenance', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='maintenance_required',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Maintenance needed before next use', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='parking_brake',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Parking brake operational', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='rear_vision_mirrors',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Rear vision mirrors properly adjusted', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='service_brakes',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Service brakes including trailer brake connections', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='steering_mechanism',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Steering mechanism responsive', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tires_condition',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Tires - proper pressure, no damage', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='trailer',
            field=models.ForeignKey(blank=True, help_text='Trailer being inspected', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.trailer'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='trailer_attached_properly',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Trailer attachment secure', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='trailer_lights_working',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Trailer lights operational', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Trip context for pre/post-trip inspections', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.trips'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='trip_completed_successfully',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Trip completed without issues', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vehicle_exterior_condition',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Overall vehicle exterior condition', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vehicle_safe_to_operate',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Vehicle safe for continued operation', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='wheels_and_rims',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Wheels and rims - no cracks or damage', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='windshield_wipers',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='fail', help_text='Windshield wipers operational', max_length=10),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='defects_found',
            field=models.BooleanField(default=False, help_text='Were any defects identified during inspection?'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver performing inspection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.driver'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Legacy field - use completed_at instead'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('pre_trip', 'Pre-Trip Inspection'), ('post_trip', 'Post-Trip Inspection'), ('annual', 'Annual DOT Inspection (CFR 396.17)'), ('dot_roadside', 'DOT Roadside Inspection'), ('maintenance', 'Maintenance Inspection'), ('quarterly', 'Quarterly Safety Inspection')], help_text='Type of inspection being performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='notes',
            field=models.TextField(blank=True, help_text='Legacy notes field', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='overall_status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Legacy field - calculated from individual checks', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='signed_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Legacy signature timestamp'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='signed_by',
            field=models.CharField(blank=True, help_text='Legacy signature field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='truck',
            field=models.ForeignKey(blank=True, help_text='Truck being inspected', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='MercAPI.truck'),
        ),
        migrations.AlterModelTable(
            name='inspection',
            table='inspections',
        ),
    ]
