# Generated by Django 4.2.20 on 2025-12-04 09:50

from django.db import migrations


def transfer_trip_inspections_to_inspections(apps, schema_editor):
    """
    Skip data transfer - inspection data will be recreated fresh.
    This migration safely handles both local (with data) and Render (existing data ignored).
    """
    print("Skipping TripInspection data transfer - using fresh unified Inspection model")
    print("Any existing inspection data will be replaced with new inspections going forward")
    # No-op: Let old inspection data be discarded, new inspections will use unified model
def reverse_transfer(apps, schema_editor):
    """Reverse operation - no-op since we didn't transfer data"""
    print("Reverse migration: No data to clean up (transfer was skipped)")


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0035_alter_inspection_options_inspection_brakes_working_and_more'),
    ]

    operations = [
        migrations.RunPython(
            transfer_trip_inspections_to_inspections,
            reverse_transfer,
        ),
    ]
