# Generated by Django 4.2.20 on 2025-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0036_transfer_tripinspection_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinspectionrepaircertification',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_certifications', to='MercAPI.inspection'),
        ),
        migrations.AlterField(
            model_name='vehicleoperationstatus',
            name='related_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.inspection'),
        ),
        migrations.DeleteModel(
            name='TripInspection',
        ),
    ]
