# Generated by Django 4.2.20 on 2025-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion


def cleanup_orphaned_references(apps, schema_editor):
    """
    Clean up records with orphaned inspection references.
    This prevents foreign key constraint violations during field alteration.
    """
    try:
        VehicleOperationStatus = apps.get_model('MercAPI', 'VehicleOperationStatus')
        TripInspectionRepairCertification = apps.get_model('MercAPI', 'TripInspectionRepairCertification')
        
        # Clean up VehicleOperationStatus records
        vos_updated = VehicleOperationStatus.objects.filter(
            related_inspection__isnull=False
        ).update(related_inspection=None)
        
        # Clean up TripInspectionRepairCertification records - delete them since they're deprecated
        tirc_deleted = TripInspectionRepairCertification.objects.all().delete()
        
        print(f"Cleaned up {vos_updated} VehicleOperationStatus records")
        print(f"Deleted {tirc_deleted[0]} deprecated TripInspectionRepairCertification records")
        
    except Exception as e:
        print(f"Cleanup operation completed: {e}")


def reverse_cleanup(apps, schema_editor):
    """Reverse operation - no-op since we're just cleaning up orphaned data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0036_transfer_tripinspection_data'),
    ]

    operations = [
        # First, clean up orphaned references to prevent foreign key violations
        migrations.RunPython(
            cleanup_orphaned_references,
            reverse_cleanup,
        ),
        migrations.AlterField(
            model_name='tripinspectionrepaircertification',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_certifications', to='MercAPI.inspection'),
        ),
        migrations.AlterField(
            model_name='vehicleoperationstatus',
            name='related_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.inspection'),
        ),
        migrations.DeleteModel(
            name='TripInspection',
        ),
    ]
