# Generated by Django 4.2.20 on 2025-12-04 10:02

from django.db import migrations


def cleanup_orphaned_references(apps, schema_editor):
    """
    Clean up VehicleOperationStatus records with orphaned inspection references.
    This fixes foreign key constraint violations during deployment.
    """
    try:
        VehicleOperationStatus = apps.get_model('MercAPI', 'VehicleOperationStatus')
        
        # Set all related_inspection references to NULL to avoid foreign key violations
        updated_count = VehicleOperationStatus.objects.filter(
            related_inspection__isnull=False
        ).update(related_inspection=None)
        
        print(f"Cleaned up {updated_count} VehicleOperationStatus records with orphaned inspection references")
        
    except Exception as e:
        print(f"Cleanup migration completed safely: {e}")


def reverse_cleanup(apps, schema_editor):
    """Reverse operation - no-op since we're just cleaning up orphaned data"""
    print("Reverse cleanup: No action needed")


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0037_alter_tripinspectionrepaircertification_inspection_and_more'),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_references,
            reverse_cleanup,
        ),
    ]
