# Generated by Django 4.2.16 on 2026-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0038_cleanup_vehicle_operation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualinspection',
            name='inspector',
        ),
        migrations.AddField(
            model_name='annualinspection',
            name='inspector_name',
            field=models.CharField(default='Unknown Inspector', help_text='Name of the inspector who performed the inspection', max_length=255),
        ),
        migrations.DeleteModel(
            name='QualifiedInspector',
        ),
    ]
