# Generated by Django 4.2.16 on 2026-03-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0039_remove_inspector_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='engine_fluids_ok',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Engine oil, coolant, brake fluid levels', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='maintenance_required',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Maintenance needed before next use', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vehicle_exterior_condition',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Overall vehicle exterior condition', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vehicle_safe_to_operate',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], help_text='Vehicle safe for continued operation', max_length=10, null=True),
        ),
    ]
