# Generated by Django 4.2.16 on 2026-03-06 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0040_simplify_inspection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When inspection was completed'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Legacy field - use completed_at instead'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='signed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Legacy signature timestamp'),
        ),
    ]
