# Generated by Django 4.2.16 on 2026-03-30 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0041_fix_timezone_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer/shipper business name', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('billing_email', models.EmailField(blank=True, help_text='Email for sending invoices', max_length=254)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('due_on_receipt', 'Due on Receipt'), ('prepaid', 'Prepaid')], default='net_30', max_length=20)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='MercAPI.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.CharField(help_text='Auto-generated load reference number', max_length=50, unique=True)),
                ('customer_reference', models.CharField(blank=True, help_text='Customer PO# or reference', max_length=100)),
                ('bol_number', models.CharField(blank=True, help_text='Bill of Lading number', max_length=100)),
                ('pickup_name', models.CharField(blank=True, help_text='Shipper/pickup facility name', max_length=255)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('pickup_city', models.CharField(blank=True, max_length=100)),
                ('pickup_state', models.CharField(blank=True, max_length=50)),
                ('pickup_zip', models.CharField(blank=True, max_length=20)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_notes', models.TextField(blank=True, help_text='Pickup instructions, appointment times, etc.')),
                ('delivery_name', models.CharField(blank=True, help_text='Consignee/delivery facility name', max_length=255)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=50)),
                ('delivery_zip', models.CharField(blank=True, max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Delivery instructions, appointment times, etc.')),
                ('commodity', models.CharField(blank=True, help_text='Description of freight', max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=10, null=True)),
                ('pieces', models.PositiveIntegerField(blank=True, help_text='Number of pieces/pallets', null=True)),
                ('equipment_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('step_deck', 'Step Deck'), ('lowboy', 'Lowboy'), ('tanker', 'Tanker'), ('power_only', 'Power Only'), ('box_truck', 'Box Truck'), ('hotshot', 'Hotshot'), ('other', 'Other')], default='dry_van', max_length=20)),
                ('temperature_requirement', models.CharField(choices=[('none', 'None (Dry)'), ('frozen', 'Frozen (-10°F to 0°F)'), ('cold', 'Cold (32°F to 40°F)'), ('cool', 'Cool (40°F to 55°F)'), ('custom', 'Custom Temperature')], default='none', max_length=10)),
                ('temperature_value', models.CharField(blank=True, help_text='Specific temp if custom', max_length=50)),
                ('hazmat', models.BooleanField(default=False)),
                ('customer_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate charged to customer', max_digits=12, null=True)),
                ('carrier_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost paid to carrier (broker mode)', max_digits=12, null=True)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Fuel surcharge amount', max_digits=10)),
                ('accessorial_charges', models.DecimalField(decimal_places=2, default=0, help_text='Detention, lumper, etc.', max_digits=10)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total billed to customer', max_digits=12, null=True)),
                ('estimated_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('booked', 'Booked'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='quoted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='MercAPI.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='MercAPI.customer')),
                ('trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load', to='MercAPI.trips')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
                'ordering': ['-created_at'],
            },
        ),
    ]
