# Generated by Django 4.2.16 on 2026-03-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0043_invoice_invoicepayment_load_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Carrier company name', max_length=255)),
                ('mc_number', models.CharField(blank=True, help_text='Motor Carrier number (MC-XXXXXX)', max_length=20)),
                ('dot_number', models.CharField(blank=True, help_text='USDOT number', max_length=20)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiration', models.DateField(blank=True, null=True)),
                ('cargo_insurance_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo insurance coverage limit', max_digits=12, null=True)),
                ('liability_insurance_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Liability insurance coverage limit', max_digits=12, null=True)),
                ('equipment_types', models.CharField(blank=True, help_text='Comma-separated equipment types (dry_van, reefer, flatbed, etc.)', max_length=255)),
                ('service_area', models.CharField(blank=True, help_text='Geographic service area (e.g., Southeast US, Nationwide)', max_length=255)),
                ('hazmat_certified', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('quick_pay', 'Quick Pay')], default='net_30', max_length=20)),
                ('factoring_company', models.CharField(blank=True, help_text='Factoring company name if applicable', max_length=255)),
                ('safety_rating', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('conditional', 'Conditional'), ('unsatisfactory', 'Unsatisfactory'), ('not_rated', 'Not Rated')], default='not_rated', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='MercAPI.company')),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='Assigned carrier (broker mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='MercAPI.carrier'),
        ),
    ]
