# Generated by Django 4.2.16 on 2026-03-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0044_carrier_load_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=50)),
                ('equipment_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('step_deck', 'Step Deck'), ('lowboy', 'Lowboy'), ('tanker', 'Tanker'), ('power_only', 'Power Only'), ('box_truck', 'Box Truck'), ('hotshot', 'Hotshot'), ('other', 'Other')], default='dry_van', max_length=20)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('per_mile', 'Per Mile')], default='flat', max_length=10)),
                ('customer_rate', models.DecimalField(decimal_places=2, help_text='Rate charged to customer', max_digits=12)),
                ('carrier_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Expected carrier cost for margin calculation', max_digits=12, null=True)),
                ('estimated_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_surcharge_pct', models.DecimalField(decimal_places=2, default=0, help_text='Fuel surcharge as percentage of customer rate', max_digits=5)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_lanes', to='MercAPI.company')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer-specific rate. Leave blank for default rate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_lanes', to='MercAPI.customer')),
            ],
            options={
                'verbose_name': 'Rate Lane',
                'verbose_name_plural': 'Rate Lanes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelSurchargeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Fuel Schedule 2025', max_length=100)),
                ('base_fuel_price', models.DecimalField(decimal_places=3, help_text='Base DOE fuel price (no surcharge below this)', max_digits=6)),
                ('surcharge_per_gallon_increment', models.DecimalField(decimal_places=3, default=0.01, help_text='Fuel price increment per step', max_digits=6)),
                ('surcharge_rate_per_mile', models.DecimalField(decimal_places=3, default=0.01, help_text='Surcharge per mile per increment', max_digits=6)),
                ('current_fuel_price', models.DecimalField(blank=True, decimal_places=3, help_text='Current DOE national average diesel price', max_digits=6, null=True)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_surcharge_schedules', to='MercAPI.company')),
            ],
            options={
                'verbose_name': 'Fuel Surcharge Schedule',
                'verbose_name_plural': 'Fuel Surcharge Schedules',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='AccessorialCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Lumper Fee, Detention, TONU', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code, e.g., DET, TONU, LUM', max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_unit', models.CharField(choices=[('flat', 'Flat Fee'), ('per_hour', 'Per Hour'), ('per_mile', 'Per Mile'), ('per_unit', 'Per Unit'), ('percentage', 'Percentage of Line Haul')], default='flat', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessorial_charges', to='MercAPI.company')),
            ],
            options={
                'verbose_name': 'Accessorial Charge',
                'verbose_name_plural': 'Accessorial Charges',
                'ordering': ['name'],
            },
        ),
    ]
