# Generated by Django 4.2.16 on 2026-03-30 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0045_ratelane_fuelsurchargeschedule_accessorialcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdocument',
            name='is_signed',
            field=models.BooleanField(default=False, help_text='Whether document has been e-signed'),
        ),
        migrations.AddField(
            model_name='tripdocument',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64-encoded signature image'),
        ),
        migrations.AddField(
            model_name='tripdocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdocument',
            name='signed_by_name',
            field=models.CharField(blank=True, help_text='Name of the signer', max_length=255),
        ),
        migrations.AlterField(
            model_name='tripdocument',
            name='document_type',
            field=models.CharField(choices=[('bol', 'Bill of Lading'), ('pod', 'Proof of Delivery'), ('rate_confirmation', 'Rate Confirmation'), ('carrier_packet', 'Carrier Packet'), ('lumper_receipt', 'Lumper Receipt'), ('receipt', 'Receipt'), ('photo', 'Photo'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tripdocument',
            name='file',
            field=models.FileField(upload_to='trip_documents/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='LoadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('rate_confirmation', 'Rate Confirmation'), ('bol', 'Bill of Lading'), ('pod', 'Proof of Delivery'), ('carrier_packet', 'Carrier Packet'), ('lumper_receipt', 'Lumper Receipt'), ('invoice', 'Invoice'), ('weight_ticket', 'Weight Ticket'), ('customs', 'Customs Document'), ('receipt', 'Receipt'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='load_documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=False, help_text='Whether document has been e-signed')),
                ('signed_by_name', models.CharField(blank=True, help_text='Name of the signer', max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64-encoded signature image')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='MercAPI.load')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Load Document',
                'verbose_name_plural': 'Load Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
