# Generated by Django 4.2.16 on 2026-03-30 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def generate_unique_tracking_tokens(apps, schema_editor):
    """Populate existing Load rows with unique UUIDs."""
    Load = apps.get_model('MercAPI', 'Load')
    for load in Load.objects.all():
        load.tracking_token = uuid.uuid4()
        load.save(update_fields=['tracking_token'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0046_tripdocument_is_signed_tripdocument_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='current_eta',
            field=models.DateTimeField(blank=True, help_text='Current ETA to delivery', null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='customer_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send email notifications to customer at milestones'),
        ),
        migrations.AddField(
            model_name='load',
            name='last_known_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='last_known_location',
            field=models.CharField(blank=True, help_text='Last reported location', max_length=255),
        ),
        migrations.AddField(
            model_name='load',
            name='last_known_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        # Step 1: Add tracking_token without unique constraint
        migrations.AddField(
            model_name='load',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public token for customer tracking portal', null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_tracking_tokens, migrations.RunPython.noop),
        # Step 3: Add unique constraint and remove null
        migrations.AlterField(
            model_name='load',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public token for customer tracking portal', unique=True),
        ),
        migrations.CreateModel(
            name='LoadTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Load Created'), ('booked', 'Load Booked'), ('dispatched', 'Dispatched'), ('driver_assigned', 'Driver Assigned'), ('carrier_assigned', 'Carrier Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('check_call', 'Check Call Received'), ('eta_updated', 'ETA Updated'), ('arrived_delivery', 'Arrived at Delivery'), ('delivered', 'Delivered'), ('pod_received', 'POD Received'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('delay', 'Delay Reported'), ('issue', 'Issue Reported')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra event data (driver name, ETA, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_customer_visible', models.BooleanField(default=True, help_text='Show this event in the customer tracking portal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='MercAPI.load')),
            ],
            options={
                'verbose_name': 'Load Tracking Event',
                'verbose_name_plural': 'Load Tracking Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MercAPI.load')),
                ('tracking_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.loadtrackingevent')),
            ],
            options={
                'verbose_name': 'Load Notification',
                'verbose_name_plural': 'Load Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('location_update', 'Location Update'), ('eta_update', 'ETA Update'), ('pickup_arrived', 'Arrived at Pickup'), ('pickup_completed', 'Pickup Completed'), ('delivery_arrived', 'Arrived at Delivery'), ('delivery_completed', 'Delivery Completed'), ('delay', 'Delay Report'), ('issue', 'Issue Report'), ('other', 'Other')], default='location_update', max_length=30)),
                ('location', models.CharField(blank=True, help_text='Current location (city, state)', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('eta', models.DateTimeField(blank=True, help_text='Updated ETA to next stop', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_calls', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_calls', to='MercAPI.load')),
            ],
            options={
                'verbose_name': 'Check Call',
                'verbose_name_plural': 'Check Calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
