# Generated by Django 4.2.16 on 2026-03-31 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MercAPI', '0047_load_current_eta_load_customer_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal template name (e.g., 'license_expiring_30d')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('compliance', 'Safety & Compliance'), ('operations', 'Operations'), ('insurance', 'Insurance'), ('maintenance', 'Maintenance'), ('load', 'Load Updates'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, help_text='Email subject line (supports {variable} placeholders)', max_length=255)),
                ('body', models.TextField(help_text='Message body (supports {variable} placeholders)')),
                ('html_template', models.CharField(blank=True, help_text="Path to Django HTML template for email (e.g., 'emails/license_expiring.html')", max_length=255)),
                ('whatsapp_template_id', models.CharField(blank=True, help_text='Twilio-approved WhatsApp template SID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('compliance', 'Safety & Compliance'), ('operations', 'Operations'), ('insurance', 'Insurance'), ('maintenance', 'Maintenance'), ('load', 'Load Updates'), ('system', 'System')], help_text='Notification category this preference applies to', max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], default='immediate', max_length=20)),
                ('whatsapp_phone', models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +1234567890)', max_length=20)),
                ('sms_phone', models.CharField(blank=True, help_text='SMS number with country code', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Don't send notifications after this time (user's local time)", null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text="Resume notifications after this time (user's local time)", null=True)),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone for quiet hours", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['user', 'category'],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('compliance', 'Safety & Compliance'), ('operations', 'Operations'), ('insurance', 'Insurance'), ('maintenance', 'Maintenance'), ('load', 'Load Updates'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, help_text='Twilio Message SID or other external tracking ID', max_length=100)),
                ('related_object_type', models.CharField(blank=True, help_text="Model name of related object (e.g., 'Driver', 'Load', 'Truck')", max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object that triggered this notification', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (e.g., days until expiry, inspection details)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='User who received this notification (null for external recipients)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.notificationtemplate')),
                ('tenant', models.ForeignKey(help_text='Tenant this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MercAPI.tenant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='MercAPI_not_tenant__42409c_idx'), models.Index(fields=['recipient', '-created_at'], name='MercAPI_not_recipie_0fc8e9_idx'), models.Index(fields=['status'], name='MercAPI_not_status_f57635_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='MercAPI_not_related_3fb7fd_idx')],
            },
        ),
    ]
