# Generated by Django 4.2.16 on 2026-03-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0048_notificationtemplate_notificationpreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_phone',
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
    ]
