# Generated by Django 4.2.16 on 2026-03-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0049_remove_sms_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadnotification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
