# Generated by Django 4.2.16 on 2026-04-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0051_notification_is_read'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='MercAPI_not_recipie_4ad037_idx',
            old_name='mercapi_notif_recip_read_idx',
        ),
    ]
