# Generated by Django 4.2.16 on 2026-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0053_companynotificationsetting_notification_in_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companynotificationsetting',
            name='whatsapp_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='whatsapp_phone',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='whatsapp_template_id',
        ),
        migrations.AlterField(
            model_name='loadnotification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='external_id',
            field=models.CharField(blank=True, help_text='External tracking ID for delivery confirmation', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email')], max_length=10),
        ),
    ]
