# Generated by Django 4.2.16 on 2026-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0055_company_company_type_company_dot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='breakdown_description',
            field=models.TextField(blank=True, help_text='Driver description of breakdown', null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='breakdown_location',
            field=models.CharField(blank=True, help_text='Location where breakdown occurred', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='breakdown_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='breakdown_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='delivery_confirmed',
            field=models.BooleanField(default=False, help_text='Driver confirmed delivery at destination'),
        ),
        migrations.AddField(
            model_name='trips',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='pod_uploaded',
            field=models.BooleanField(default=False, help_text='Proof of Delivery uploaded by driver'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('failed_inspection', 'Failed Inspection'), ('maintenance_hold', 'Maintenance Hold'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('breakdown', 'Breakdown'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
