# Generated by Django 4.2.16 on 2026-04-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercAPI', '0056_add_driver_workflow_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('motive', 'Motive (KeepTruckin)'), ('samsara', 'Samsara'), ('geotab', 'Geotab')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('pending', 'Pending Setup')], default='pending', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='Encrypted API key for this provider', max_length=512)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_providers', to='MercAPI.company')),
            ],
            options={
                'verbose_name': 'ELD Provider Connection',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_mph', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('heading', models.IntegerField(blank=True, help_text='Compass heading 0-360', null=True)),
                ('odometer_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(help_text='Timestamp from ELD device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_provider', models.CharField(blank=True, max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MercAPI.driver')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_locations', to='MercAPI.load')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='MercAPI.truck')),
            ],
            options={
                'verbose_name': 'Vehicle Location',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['truck', '-recorded_at'], name='MercAPI_veh_truck_i_2a7ede_idx'), models.Index(fields=['-recorded_at'], name='MercAPI_veh_recorde_b8fc71_idx')],
            },
        ),
        migrations.CreateModel(
            name='ELDVehicleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_vehicle_id', models.CharField(help_text='Vehicle ID in the ELD system', max_length=255)),
                ('external_vehicle_name', models.CharField(blank=True, max_length=255)),
                ('auto_matched', models.BooleanField(default=False, help_text='True if matched by VIN automatically')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eld_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_mappings', to='MercAPI.eldprovider')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_mappings', to='MercAPI.truck')),
            ],
            options={
                'verbose_name': 'ELD Vehicle Mapping',
                'unique_together': {('eld_provider', 'external_vehicle_id')},
            },
        ),
        migrations.CreateModel(
            name='ELDDriverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_driver_id', models.CharField(help_text='Driver ID in the ELD system', max_length=255)),
                ('external_driver_name', models.CharField(blank=True, max_length=255)),
                ('auto_matched', models.BooleanField(default=False, help_text='True if matched by name automatically')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_mappings', to='MercAPI.driver')),
                ('eld_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_mappings', to='MercAPI.eldprovider')),
            ],
            options={
                'verbose_name': 'ELD Driver Mapping',
                'unique_together': {('eld_provider', 'external_driver_id')},
            },
        ),
    ]
